### ISSUE TITLE
Results on FDDB

### ISSUE THREAD

**Issue by tensorboy** [xiezheng-cs/mtcnn_pytorch#1]
Hi, @xiezheng-cs 

Thanks for your great work, do you have the result on FDDB?

**Comment by xiezheng-cs** [comment]
I didn't do it, but you can try it if you want.  
https://github.com/xiezheng-cs/mtcnn_pytorch/blob/master/test_on_FDDB.py

**Comment by tensorboy** [comment]
Thanks!
